### ISSUE TITLE
Sinric Pro library 3.0.0 how to set and check the powerstates with this latest library? 

### ISSUE THREAD

**Issue by praneet-bhagat** [sinricpro/help-docs#25]
Bug: I recently updated to Sinric Pro library ver. 3.0.0. This version doesn't support the onPowerState method and gives below error 'using SinricProMotionsensor = class SINRICPRO_3_0_0::SinricProMotionsensor' {aka 'class SINRICPRO_3_0_0::SinricProMotionsensor'} has no member named 'onPowerState'
 
Is there a way to get and set the PowerStates using this new library version?

**Comment by kakopappa** [comment]
hi @praneet-bhagat 

onPowerState has been removed from all the sensors in 3.0.0. 

Your options are
1. remove it from your code as well. example: https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/MotionSensor/MotionSensor.ino

2. use the old library 

3. use a custom device type with power on/off + contact sensor.  
https://help.sinric.pro/pages/custom-templates

**Comment by praneet-bhagat** [comment]
Got it! This was good functionality to use over Alexa or other supported voice-controlled virtual assistants.

**Comment by praneet-bhagat** [comment]
Hi Aruna,

I did see this response from kakopappa
<https://github.com/sinricpro/feature-requests/commits?author=kakopappa> and
closed the ticket already, however could you be kind enough to tell me the
reason for this?

The challenge with the onPowerState function being taken off from all
sensors in 3.0.0 is that the arduino IDE keeps annoying with asking to
update the library with the latest version and this functionality was
useful with the voice command feature.

Are there any possibilities of reinstating this feature in the future
releases?

Regards,

Praneet

**Comment by kakopappa** [comment]
sensors do not need to turn on/off like a switch. they need to be constantly on and working. If you need to turn on/off please consider using a custom device type.

**Comment by praneet-bhagat** [comment]
ok thanks.
