### ISSUE TITLE
not working in Google Home, only with Alexa

### ISSUE THREAD

**Issue by societyofrobots** [sinricpro/help-docs#6]
I followed [all the tutorials](https://help.sinric.pro/pages/googlehome.html), but my Google Home app is not displaying anything added via Smart Things. It works great with Alexa, though.

Is this working for anyone else in Google Home?

note: I wasn't sure if I previously posted this in the right project, so I apologize for any duplication
https://github.com/kakopappa/sinric/issues/455

**Comment by kakopappa** [comment]
@societyofrobots I think the time you tested the Google Home - SmartThings, Smart things had some connectivity network issues.

![image](https://user-images.githubusercontent.com/7474406/99894106-29632c00-2cb5-11eb-93f0-9cc4253a4cb5.png)

I just tested the complete integration and all works fine. Make sure to change the device status to on/off on the server before you link the SmartThings-Google Home. Unless you don't do this the server doesn't know the current status of the device

If the problem persists please raise an issue here https://github.com/sinricpro/non-sdk-issues
